package com.dimitribelfor.tfttracker.config

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties
class ConfigurationPropertiesConfig